-- CREATE TABLE t_baseinfo
-- (
--     id VARCHAR DEFAULT 企业id,
--     name VARCHAR DEFAULT 企业名,
--     percentile_score VARCHAR DEFAULT 企业评分,
--     staff_num_range VARCHAR DEFAULT 人员规模,
--     from_time VARCHAR DEFAULT 经营开始时间,
--     type VARCHAR DEFAULT 法人类型,
--     bond_name VARCHAR DEFAULT 股票名,
--     is_micro_ent VARCHAR DEFAULT 是否是小微企业,
--     used_bond_name VARCHAR DEFAULT 股票曾用名,
--     reg_number VARCHAR DEFAULT 注册号,
--     reg_capital VARCHAR DEFAULT 注册资本,
--     reg_institute VARCHAR DEFAULT 登记机关,
--     reg_location VARCHAR DEFAULT 注册地址,
--     industry VARCHAR DEFAULT 行业,
--     approved_time VARCHAR DEFAULT 核准时间,
--     social_staff_num VARCHAR DEFAULT 参保人数,
--     tags VARCHAR DEFAULT 企业标签,
--     tax_number VARCHAR DEFAULT 纳税人识别号,
--     business_scope VARCHAR DEFAULT 经营范围,
--     property3 VARCHAR DEFAULT 英文名,
--     alias VARCHAR DEFAULT 简称,
--     org_number VARCHAR DEFAULT 组织机构代码,
--     reg_status VARCHAR DEFAULT 企业状态,
--     estiblish_time VARCHAR DEFAULT 成立日期,
--     bond_type VARCHAR DEFAULT 股票类型,
--     legal_person_name VARCHAR DEFAULT 法人,
--     to_time VARCHAR DEFAULT 经营结束时间,
--     actual_capital VARCHAR DEFAULT 实收注册资金,
--     company_org_type VARCHAR DEFAULT 企业类型,
--     base VARCHAR DEFAULT 省份简称,
--     credit_code VARCHAR DEFAULT 统一社会信用代码,
--     history_names VARCHAR DEFAULT 曾用名,
--     bond_num VARCHAR DEFAULT 股票号,
--     reg_capital_currency VARCHAR DEFAULT 注册资本币种,
--     actual_capital_currency VARCHAR DEFAULT 实收注册资本币种,
--     email VARCHAR DEFAULT 邮箱,
--     website_list VARCHAR DEFAULT 网址,
--     phone_number VARCHAR DEFAULT 企业联系方式,
--     revoke_date VARCHAR DEFAULT 吊销日期,
--     revoke_reason VARCHAR DEFAULT 吊销原因,
--     cancel_date VARCHAR DEFAULT 注销日期,
--     cancel_reason VARCHAR DEFAULT 注销原因
-- )
CREATE TABLE t_baseinfo
(
  id VARCHAR DEFAULT "",
  name VARCHAR DEFAULT "",
  percentile_score VARCHAR DEFAULT "",
  staff_num_range VARCHAR DEFAULT "",
  from_time VARCHAR DEFAULT "",
  type VARCHAR DEFAULT "",
  bond_name VARCHAR DEFAULT "",
  is_micro_ent VARCHAR DEFAULT "",
  used_bond_name VARCHAR DEFAULT "",
  reg_number VARCHAR DEFAULT "",
  reg_capital VARCHAR DEFAULT "",
  reg_institute VARCHAR DEFAULT "",
  reg_location VARCHAR DEFAULT "",
  industry VARCHAR DEFAULT "",
  approved_time VARCHAR DEFAULT "",
  social_staff_num VARCHAR DEFAULT "",
  tags VARCHAR DEFAULT "",
  tax_number VARCHAR DEFAULT "",
  business_scope VARCHAR DEFAULT "",
  property3 VARCHAR DEFAULT "",
  alias VARCHAR DEFAULT "",
  org_number VARCHAR DEFAULT "",
  reg_status VARCHAR DEFAULT "",
  estiblish_time VARCHAR DEFAULT "",
  bond_type VARCHAR DEFAULT "",
  legal_person_name VARCHAR DEFAULT "",
  to_time VARCHAR DEFAULT "",
  actual_capital VARCHAR DEFAULT "",
  company_org_type VARCHAR DEFAULT "",
  base VARCHAR DEFAULT "",
  credit_code VARCHAR DEFAULT "",
  history_names VARCHAR DEFAULT "",
  bond_num VARCHAR DEFAULT "",
  reg_capital_currency VARCHAR DEFAULT "",
  actual_capital_currency VARCHAR DEFAULT "",
  email VARCHAR DEFAULT "",
  website_list VARCHAR DEFAULT "",
  phone_number VARCHAR DEFAULT "",
  revoke_date VARCHAR DEFAULT "",
  revoke_reason VARCHAR DEFAULT "",
  cancel_date VARCHAR DEFAULT "",
  cancel_reason VARCHAR DEFAULT ""
)